# Load Library

In [3]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_rel, wilcoxon
from scipy.stats import friedmanchisquare

# Load results

In [1]:
imputation_results_raw_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/imputation_results_raw_datav2.csv'
imputation_results_seed42_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/imputation_results_seed42_datav2.csv'
imputation_results_summary_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/imputation_results_summary_datav2.csv'

In [2]:
downstream_results_raw_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/downstream_results_raw_datav2.csv'
downstream_results_summary_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/downstream_results_summary_datav2.csv'
downstream_auc_diff_vs_full_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/downstream_auc_diff_vs_full_datav2.csv'
downstream_friedman_by_scenario_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/downstream_friedman_by_scenario_datav2.csv'
downstream_pooled_posthoc_datav2 ='/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/downstream_pooled_posthoc_datav2.csv'

# 1. Statistical test

In [21]:
from scipy.stats import friedmanchisquare

def friedman_test(df, mechanism, missing_rate, metric="roc_auc"):
    methods = ["Mean", "Median", "KNN", "MICE"]
    samples = [
        df[(df["mechanism"]==mechanism) & (df["missing_rate"]==missing_rate) & (df["method"]==m)]
        .sort_values("seed")[metric].to_numpy()
        for m in methods
    ]
    stat, p = friedmanchisquare(*samples)
    print(f"{mechanism}/{missing_rate:.0%}: Friedman p = {p:.4f}")
    return p

In [22]:
def friedman_test(df, mechanism, missing_rate, metric="roc_auc"):
    """
    Friedman test: compares all 4 imputation methods at once
    (paired by seed, non-parametric, suitable for small n).
    """
    methods = ["Mean", "Median", "KNN", "MICE"]
    samples = [
        df[(df["mechanism"] == mechanism) &
           (df["missing_rate"] == missing_rate) &
           (df["method"] == m)]
        .sort_values("seed")[metric]
        .to_numpy()
        for m in methods
    ]

    stat, p = friedmanchisquare(*samples)
    return {
        "mechanism": mechanism,
        "missing_rate": missing_rate,
        "friedman_stat": stat,
        "p_value": p
    }

In [23]:

friedman_results = []
for mechanism in ["MCAR", "MAR", "MNAR"]:
    for rate in [0.1, 0.3, 0.5]:
        friedman_results.append(friedman_test(downstream_results_df, mechanism, rate))

friedman_df = pd.DataFrame(friedman_results)
friedman_df.to_csv(
    "/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/friedman_test_results.csv",
    index=False
)

print("Number of mechanism/rate combinations tested:", len(friedman_df))
print("Number significant (p < 0.05):", (friedman_df["p_value"] < 0.05).sum())
friedman_df.sort_values("p_value")

Number of mechanism/rate combinations tested: 9
Number significant (p < 0.05): 1

  mechanism  missing_rate  friedman_stat   p_value
1      MCAR           0.3           9.24  0.026264
0      MCAR           0.1           6.12  0.105916
2      MCAR           0.5           5.40  0.144744
6      MNAR           0.1           5.16  0.160449
8      MNAR           0.5           4.92  0.177750
4       MAR           0.3           4.20  0.240662
3       MAR           0.1           3.48  0.323365
7      MNAR           0.3           1.32  0.724389
5       MAR           0.5           0.60  0.896432

In [ ]:
def holm_correction(p_values, alpha=0.05):
    p_values = np.array(p_values)
    n = len(p_values)
    order = np.argsort(p_values)
    sorted_p = p_values[order]

    reject_sorted = np.zeros(n, dtype=bool)
    p_corrected_sorted = np.zeros(n)

    for i in range(n):
        p_corrected_sorted[i] = min(sorted_p[i] * (n - i), 1.0)
        # 保证校正后的p值单调不减
        if i > 0:
            p_corrected_sorted[i] = max(p_corrected_sorted[i], p_corrected_sorted[i-1])

    # 一旦某个不显著，后面（更大p值的）全部不显著
    for i in range(n):
        if p_corrected_sorted[i] <= alpha:
            reject_sorted[i] = True
        else:
            break

    reject = np.zeros(n, dtype=bool)
    p_corrected = np.zeros(n)
    reject[order] = reject_sorted
    p_corrected[order] = p_corrected_sorted

    return reject, p_corrected

reject, p_holm = holm_correction(friedman_df["p_value"].values)
friedman_df["p_holm"] = p_holm
friedman_df["significant_holm"] = reject

In [28]:
friedman_df

  mechanism  missing_rate  friedman_stat   p_value    p_holm  significant_holm
0      MCAR           0.1           6.12  0.105916  0.847326             False
1      MCAR           0.3           9.24  0.026264  0.236380             False
2      MCAR           0.5           5.40  0.144744  1.000000             False
3       MAR           0.1           3.48  0.323365  1.000000             False
4       MAR           0.3           4.20  0.240662  1.000000             False
5       MAR           0.5           0.60  0.896432  1.000000             False
6      MNAR           0.1           5.16  0.160449  1.000000             False
7      MNAR           0.3           1.32  0.724389  1.000000             False
8      MNAR           0.5           4.92  0.177750  1.000000             False

In [29]:
friedman_df = pd.DataFrame(friedman_results)
friedman_df.to_csv(
    "/Users/sivhoung/Desktop/Year 4 intern project/Project code /results/friedman_test_results.csv",
    index=False
)

# 2. Imputation results vs Downstream performance

In [ ]:
summary_df = (
    downstream_results_df
    .groupby(["mechanism", "missing_rate", "method"])
    .agg(
        accuracy_mean=("accuracy", "mean"), accuracy_std=("accuracy", "std"),
        precision_mean=("precision", "mean"), precision_std=("precision", "std"),
        recall_mean=("recall", "mean"), recall_std=("recall", "std"),
        f1_mean=("f1", "mean"), f1_std=("f1", "std"),
        roc_auc_mean=("roc_auc", "mean"), roc_auc_std=("roc_auc", "std"),
    )
    .reset_index()
)

summary_df

,mechanism,missing_rate,method,accuracy_mean,accuracy_std,precision_mean,precision_std,recall_mean,recall_std,f1_mean,f1_std,roc_auc_mean,roc_auc_std
0,Baseline,0.0,Drop_column,0.650459,0.009861,0.108201,0.003144,0.457363,0.012390,0.174980,0.004559,0.584970,0.005395
1,Baseline,0.0,Full_data,0.639225,0.006161,0.108520,0.002825,0.478585,0.017084,0.176913,0.004743,0.592370,0.006143
2,MAR,0.1,KNN,0.639840,0.007178,0.108535,0.003022,0.477685,0.020736,0.176865,0.005226,0.590689,0.005369
3,MAR,0.1,MICE,0.639569,0.005124,0.108652,0.002364,0.478714,0.013631,0.177100,0.003912,0.590884,0.003882
4,MAR,0.1,Mean,0.636150,0.006326,0.108337,0.001591,0.482830,0.015153,0.176955,0.002921,0.592478,0.005586
5,MAR,0.1,Median,0.634754,0.008143,0.107950,0.003135,0.482830,0.015153,0.176437,0.004895,0.591585,0.005347
6,MAR,0.3,KNN,0.640694,0.008111,0.107712,0.002998,0.471511,0.018389,0.175347,0.004939,0.589425,0.004645
7,MAR,0.3,MICE,0.640652,0.005151,0.108051,0.002957,0.473441,0.013284,0.175941,0.004722,0.589534,0.004709
8,MAR,0.3,Mean,0.641861,0.008762,0.108752,0.002640,0.475113,0.008892,0.176976,0.003707,0.591769,0.004854
9,MAR,0.3,Median,0.641986,0.006358,0.108126,0.002667,0.471768,0.020125,0.175916,0.004772,0.590007,0.005521
10,MAR,0.5,KNN,0.641778,0.007551,0.108046,0.003316,0.471511,0.017911,0.175792,0.005372,0.588188,0.005816
11,MAR,0.5,MICE,0.641715,0.008968,0.107389,0.002328,0.467910,0.014934,0.174666,0.003597,0.588587,0.003706
12,MAR,0.5,Mean,0.640277,0.007310,0.107268,0.002400,0.469839,0.018917,0.174644,0.004238,0.588704,0.006929
13,MAR,0.5,Median,0.639892,0.006698,0.106625,0.003041,0.466752,0.014822,0.173584,0.004843,0.588821,0.007449
14,MCAR,0.1,KNN,0.640767,0.007252,0.109277,0.001618,0.480129,0.012607,0.178020,0.002580,0.595388,0.003537
15,MCAR,0.1,MICE,0.643570,0.005789,0.108964,0.002856,0.473698,0.019371,0.177162,0.004975,0.591499,0.005897
16,MCAR,0.1,Mean,0.640934,0.004454,0.109231,0.002716,0.479614,0.013607,0.177932,0.004432,0.594088,0.007093
17,MCAR,0.1,Median,0.641392,0.006485,0.109305,0.001276,0.479228,0.011818,0.177997,0.002132,0.591714,0.003767
18,MCAR,0.3,KNN,0.644810,0.008555,0.107950,0.002660,0.465723,0.013229,0.175257,0.004003,0.588493,0.005254
19,MCAR,0.3,MICE,0.644206,0.007055,0.107194,0.002337,0.462765,0.016724,0.174053,0.004008,0.583863,0.006537
20,MCAR,0.3,Mean,0.640788,0.007240,0.107564,0.002737,0.470611,0.019025,0.175091,0.004708,0.587664,0.006194
21,MCAR,0.3,Median,0.642976,0.006653,0.106497,0.002047,0.460965,0.014533,0.173009,0.003441,0.586674,0.004529
22,MCAR,0.5,KNN,0.646957,0.007355,0.107733,0.002813,0.460965,0.014967,0.174635,0.004460,0.588810,0.006298
23,MCAR,0.5,MICE,0.647957,0.007196,0.108142,0.001917,0.461608,0.016360,0.175216,0.003409,0.585576,0.006302
24,MCAR,0.5,Mean,0.645425,0.011810,0.107572,0.002972,0.462508,0.016517,0.174515,0.004382,0.585809,0.005666
25,MCAR,0.5,Median,0.645206,0.007792,0.107086,0.002896,0.460450,0.017612,0.173746,0.004799,0.586450,0.005423
26,MNAR,0.1,KNN,0.638850,0.005006,0.108430,0.003492,0.478714,0.018010,0.176806,0.005771,0.589819,0.005979
27,MNAR,0.1,MICE,0.640809,0.004901,0.108603,0.002548,0.476399,0.017047,0.176875,0.004430,0.591622,0.007062
28,MNAR,0.1,Mean,0.637516,0.008556,0.107530,0.003163,0.475756,0.015537,0.175397,0.004921,0.591056,0.007463
29,MNAR,0.1,Median,0.638620,0.008302,0.108534,0.003167,0.479743,0.022077,0.177000,0.005426,0.591730,0.007160
30,MNAR,0.3,KNN,0.641132,0.008200,0.106870,0.002265,0.465981,0.011482,0.173851,0.003388,0.588584,0.005622
31,MNAR,0.3,MICE,0.642924,0.008383,0.107278,0.002441,0.465338,0.016939,0.174342,0.004062,0.588428,0.005639
32,MNAR,0.3,Mean,0.641434,0.007439,0.107600,0.002554,0.469711,0.018730,0.175074,0.004422,0.589682,0.006993
33,MNAR,0.3,Median,0.635734,0.007065,0.106534,0.002281,0.473312,0.017117,0.173908,0.003954,0.588289,0.004691
34,MNAR,0.5,KNN,0.640798,0.005835,0.106001,0.003395,0.461736,0.013045,0.172414,0.005302,0.583720,0.005964
35,MNAR,0.5,MICE,0.645133,0.009920,0.107851,0.003442,0.464566,0.016087,0.175038,0.005227,0.585081,0.005614
36,MNAR,0.5,Mean,0.640840,0.006729,0.106725,0.001375,0.465723,0.009235,0.173645,0.001992,0.586729,0.004514
37,MNAR,0.5,Median,0.640434,0.002851,0.108062,0.000999,0.473955,0.008864,0.175994,0.001878,0.588306,0.002952

In [ ]:
comparison_df = imputation_results_df.merge(
    summary_df[["mechanism", "missing_rate", "method", "roc_auc_mean", "roc_auc_std"]],
    on=["mechanism", "missing_rate", "method"]
)

comparison_df = comparison_df.sort_values(["mechanism", "missing_rate", "MAE"])
comparison_df

,mechanism,missing_rate,method,MAE,RMSE,roc_auc_mean,roc_auc_std
0,MAR,0.1,KNN,7.127056,15.865384,0.590689,0.005369
9,MAR,0.1,MICE,7.959261,16.142786,0.590884,0.003882
27,MAR,0.1,Median,13.564738,29.464809,0.591585,0.005347
18,MAR,0.1,Mean,13.663391,27.970665,0.592478,0.005586
1,MAR,0.3,KNN,6.938995,17.389804,0.589425,0.004645
10,MAR,0.3,MICE,7.673284,17.429936,0.589534,0.004709
19,MAR,0.3,Mean,12.836971,27.846714,0.591769,0.004854
28,MAR,0.3,Median,12.949991,29.140020,0.590007,0.005521
2,MAR,0.5,KNN,6.767097,16.341668,0.588188,0.005816
11,MAR,0.5,MICE,7.224448,16.225258,0.588587,0.003706
20,MAR,0.5,Mean,12.100831,26.597818,0.588704,0.006929
29,MAR,0.5,Median,12.472031,27.708360,0.588821,0.007449
3,MCAR,0.1,KNN,5.132553,11.800811,0.595388,0.003537
12,MCAR,0.1,MICE,5.866503,12.107028,0.591499,0.005897
30,MCAR,0.1,Median,9.768141,21.208753,0.591714,0.003767
21,MCAR,0.1,Mean,11.383584,20.515166,0.594088,0.007093
4,MCAR,0.3,KNN,5.108500,11.605661,0.588493,0.005254
13,MCAR,0.3,MICE,5.840672,11.852617,0.583863,0.006537
31,MCAR,0.3,Median,9.766736,20.935556,0.586674,0.004529
22,MCAR,0.3,Mean,11.333446,20.212462,0.587664,0.006194
5,MCAR,0.5,KNN,5.167500,11.903806,0.588810,0.006298
14,MCAR,0.5,MICE,5.874027,12.222229,0.585576,0.006302
32,MCAR,0.5,Median,9.763730,21.492492,0.586450,0.005423
23,MCAR,0.5,Mean,11.374564,20.800506,0.585809,0.005666
6,MNAR,0.1,KNN,7.913070,22.917326,0.589819,0.005979
15,MNAR,0.1,MICE,8.536848,22.736763,0.591622,0.007062
24,MNAR,0.1,Mean,14.125427,35.073112,0.591056,0.007463
33,MNAR,0.1,Median,15.280772,36.717336,0.591730,0.007160
7,MNAR,0.3,KNN,7.340048,18.693859,0.588584,0.005622
16,MNAR,0.3,MICE,7.883561,18.571814,0.588428,0.005639
25,MNAR,0.3,Mean,13.101698,30.053798,0.589682,0.006993
34,MNAR,0.3,Median,14.503482,31.619229,0.588289,0.004691
8,MNAR,0.5,KNN,7.113169,17.067364,0.583720,0.005964
17,MNAR,0.5,MICE,7.378324,16.669651,0.585081,0.005614
26,MNAR,0.5,Mean,12.556655,27.969749,0.586729,0.004514
35,MNAR,0.5,Median,13.720313,28.940455,0.588306,0.002952

In [32]:
assert len(comparison_df) == len (imputation_results_df)
print('OK:',len(comparison_df),"row")

OK: 36 row

In [ ]:
from scipy.stats import pearsonr, spearmanr

pearson_r, pearson_p = pearsonr(comparison_df["MAE"], comparison_df["roc_auc_mean"])
spearman_r, spearman_p = spearmanr(comparison_df["MAE"], comparison_df["roc_auc_mean"])

print(f"Pearson r = {pearson_r:.3f}, p = {pearson_p:.3f}")
print(f"Spearman r = {spearman_r:.3f}, p = {spearman_p:.3f}")

Pearson r = 0.207, p = 0.226
Spearman r = 0.264, p = 0.120